In [7]:
import pandas as pd
import json
from pathlib import Path

In [26]:
records = []
for p in Path("/mnt/backup/PeopleGatorNamedFaces/people-gator-named-faces-evaluation/report").glob("*.json"):
    *model_name, algorithm, ext = p.name.split(".")
    model_name = ".".join(model_name[1:])
    record = json.loads(p.read_text())
    record["model_name"] = model_name
    record["algorithm"] = algorithm
    records.append(record)
df = pd.DataFrame(records)
#expand metrics dict into columns
metrics_df = df["metrics"].apply(pd.Series)
df = pd.concat([df.drop(columns=["metrics", "confusion", "support"]), metrics_df], axis=1)
df.sort_values(["algorithm", "model_name"], inplace=True)
df.set_index(["algorithm", "model_name"], inplace=True)
algo_average = df.groupby("algorithm").mean()
model_best = df.groupby("model_name").mean()
df

                                                       precision    recall  \
algorithm     model_name
agglomerative convnext_atto.cosface_ms1mv3              0.001151  0.626589
              convnext_nano.cosface_ms1mv3              0.001415  0.746436
              vit_small_patch8_gap_112.cosface_ms1mv3   0.001417  0.750580
              vit_tiny_patch8_112.adaface_ms1mv3        0.000956  0.603916
              vit_tiny_patch8_112.arcface_ms1mv3        0.001088  0.632622
              vit_tiny_patch8_112.cosface_ms1mv3        0.001153  0.635091
dbscan        convnext_atto.cosface_ms1mv3              0.000541  1.000000
              convnext_nano.cosface_ms1mv3              0.000542  1.000000
              vit_small_patch8_gap_112.cosface_ms1mv3   0.000974  0.860271
              vit_tiny_patch8_112.adaface_ms1mv3        0.000541  1.000000
              vit_tiny_patch8_112.arcface_ms1mv3        0.000555  0.993108
              vit_tiny_patch8_112.cosface_ms1mv3        0.000541  1.000000
kmeans        convnext_atto.cosface_ms1mv3              0.030986  0.400464
              convnext_nano.cosface_ms1mv3              0.032042  0.444714
              vit_small_patch8_gap_112.cosface_ms1mv3   0.031839  0.452121
              vit_tiny_patch8_112.adaface_ms1mv3        0.029039  0.384790
              vit_tiny_patch8_112.arcface_ms1mv3        0.027021  0.385306
              vit_tiny_patch8_112.cosface_ms1mv3        0.031142  0.437844
spectral      convnext_atto.cosface_ms1mv3              0.017259  0.350588
              convnext_nano.cosface_ms1mv3              0.007660  0.286306
              vit_small_patch8_gap_112.cosface_ms1mv3   0.006470  0.309967
              vit_tiny_patch8_112.adaface_ms1mv3        0.013024  0.317095
              vit_tiny_patch8_112.arcface_ms1mv3        0.014988  0.306724
              vit_tiny_patch8_112.cosface_ms1mv3        0.013345  0.332016

                                                             f1  accuracy  \
algorithm     model_name
agglomerative convnext_atto.cosface_ms1mv3             0.002298  0.705624
              convnext_nano.cosface_ms1mv3             0.002825  0.714976
              vit_small_patch8_gap_112.cosface_ms1mv3  0.002828  0.713634
              vit_tiny_patch8_112.adaface_ms1mv3       0.001910  0.658519
              vit_tiny_patch8_112.arcface_ms1mv3       0.002171  0.685467
              vit_tiny_patch8_112.cosface_ms1mv3       0.002302  0.702160
dbscan        convnext_atto.cosface_ms1mv3             0.001081  0.000541
              convnext_nano.cosface_ms1mv3             0.001083  0.002521
              vit_small_patch8_gap_112.cosface_ms1mv3  0.001946  0.522758
              vit_tiny_patch8_112.adaface_ms1mv3       0.001081  0.000541
              vit_tiny_patch8_112.arcface_ms1mv3       0.001110  0.032733
              vit_tiny_patch8_112.cosface_ms1mv3       0.001082  0.000846
kmeans        convnext_atto.cosface_ms1mv3             0.057522  0.992901
              convnext_nano.cosface_ms1mv3             0.059778  0.992432
              vit_small_patch8_gap_112.cosface_ms1mv3  0.059489  0.992267
              vit_tiny_patch8_112.adaface_ms1mv3       0.054002  0.992707
              vit_tiny_patch8_112.arcface_ms1mv3       0.050501  0.992162
              vit_tiny_patch8_112.cosface_ms1mv3       0.058148  0.992327
spectral      convnext_atto.cosface_ms1mv3             0.032898  0.988850
              convnext_nano.cosface_ms1mv3             0.014921  0.979550
              vit_small_patch8_gap_112.cosface_ms1mv3  0.012676  0.973879
              vit_tiny_patch8_112.adaface_ms1mv3       0.025021  0.986632
              vit_tiny_patch8_112.arcface_ms1mv3       0.028579  0.988720
              vit_tiny_patch8_112.cosface_ms1mv3       0.025658  0.986359

                                                        jaccard  \
algorithm     model_name
agglomerative convnext_atto.cosface_ms1mv3             0.001150
              convnext_nano.cosface_ms1mv3             0.001415
              vit_small_patch8_gap_112.cosface_ms1mv3  0.001416
              vit_tiny_patch8_112.adaface_ms1mv3       0.000956
              vit_tiny_patch8_112.arcface_ms1mv3       0.001087
              vit_tiny_patch8_112.cosface_ms1mv3       0.001152
dbscan        convnext_atto.cosface_ms1mv3             0.000541
              convnext_nano.cosface_ms1mv3             0.000542
              vit_small_patch8_gap_112.cosface_ms1mv3  0.000974
              vit_tiny_patch8_112.adaface_ms1mv3       0.000541
              vit_tiny_patch8_112.arcface_ms1mv3       0.000555
              vit_tiny_patch8_112.cosface_ms1mv3       0.000541
kmeans        convnext_atto.cosface_ms1mv3             0.029613
              convnext_nano.cosface_ms1mv3             0.030810
              vit_small_patch8_gap_112.cosface_ms1mv3  0.030656
              vit_tiny_patch8_112.adaface_ms1mv3       0.027750
              vit_tiny_patch8_112.arcface_ms1mv3       0.025905
              vit_tiny_patch8_112.cosface_ms1mv3       0.029945
spectral      convnext_atto.cosface_ms1mv3             0.016724
              convnext_nano.cosface_ms1mv3             0.007517
              vit_small_patch8_gap_112.cosface_ms1mv3  0.006378
              vit_tiny_patch8_112.adaface_ms1mv3       0.012669
              vit_tiny_patch8_112.arcface_ms1mv3       0.014497
              vit_tiny_patch8_112.cosface_ms1mv3       0.012996

                                                       fowlkes_mallows  \
algorithm     model_name
agglomerative convnext_atto.cosface_ms1mv3                    0.026854
              convnext_nano.cosface_ms1mv3                    0.032503
              vit_small_patch8_gap_112.cosface_ms1mv3         0.032607
              vit_tiny_patch8_112.adaface_ms1mv3              0.024033
              vit_tiny_patch8_112.arcface_ms1mv3              0.026230
              vit_tiny_patch8_112.cosface_ms1mv3              0.027059
dbscan        convnext_atto.cosface_ms1mv3                    0.023258
              convnext_nano.cosface_ms1mv3                    0.023281
              vit_small_patch8_gap_112.cosface_ms1mv3         0.028951
              vit_tiny_patch8_112.adaface_ms1mv3              0.023258
              vit_tiny_patch8_112.arcface_ms1mv3              0.023479
              vit_tiny_patch8_112.cosface_ms1mv3              0.023262
kmeans        convnext_atto.cosface_ms1mv3                    0.111395
              convnext_nano.cosface_ms1mv3                    0.119372
              vit_small_patch8_gap_112.cosface_ms1mv3         0.119980
              vit_tiny_patch8_112.adaface_ms1mv3              0.105706
              vit_tiny_patch8_112.arcface_ms1mv3              0.102037
              vit_tiny_patch8_112.cosface_ms1mv3              0.116770
spectral      convnext_atto.cosface_ms1mv3                    0.077786
              convnext_nano.cosface_ms1mv3                    0.046831
              vit_small_patch8_gap_112.cosface_ms1mv3         0.044784
              vit_tiny_patch8_112.adaface_ms1mv3              0.064264
              vit_tiny_patch8_112.arcface_ms1mv3              0.067802
              vit_tiny_patch8_112.cosface_ms1mv3              0.066564

                                                       rand_index  \
algorithm     model_name
agglomerative convnext_atto.cosface_ms1mv3               0.705624
              convnext_nano.cosface_ms1mv3               0.714976
              vit_small_patch8_gap_112.cosface_ms1mv3    0.713634
              vit_tiny_patch8_112.adaface_ms1mv3         0.658519
              vit_tiny_patch8_112.arcface_ms1mv3         0.685467
              vit_tiny_patch8_112.cosface_ms1mv3         0.702160
dbscan        convnext_atto.cosface_ms1mv3               0.000541
              convnext_nano.cosface_ms1mv3               0.002521
              vit_small_patch8_gap_112.cosface_ms1mv3    0.522758
              vit_tiny_patch8_112.adaface_ms1mv3         0.000541
              vit_tiny_patch8_112.arcface_ms1mv3         0.032733
              vit_tiny_patch8_112.cosface_ms1mv3         0.000846
kmeans        convnext_atto.cosface_ms1mv3               0.992901
              convnext_nano.cosface_ms1mv3               0.992432
              vit_small_patch8_gap_112.cosface_ms1mv3    0.992267
              vit_tiny_patch8_112.adaface_ms1mv3         0.992707
              vit_tiny_patch8_112.arcface_ms1mv3         0.992162
              vit_tiny_patch8_112.cosface_ms1mv3         0.992327
spectral      convnext_atto.cosface_ms1mv3               0.988850
              convnext_nano.cosface_ms1mv3               0.979550
              vit_small_patch8_gap_112.cosface_ms1mv3    0.973879
              vit_tiny_patch8_112.adaface_ms1mv3         0.986632
              vit_tiny_patch8_112.arcface_ms1mv3         0.988720
              vit_tiny_patch8_112.cosface_ms1mv3         0.986359

                                                       adjusted_rand_index
algorithm     model_name
agglomerative convnext_atto.cosface_ms1mv3                        0.344897
              convnext_nano.cosface_ms1mv3                        0.358705
              vit_small_patch8_gap_112.cosface_ms1mv3             0.376943
              vit_tiny_patch8_112.adaface_ms1mv3                  0.362289
              vit_tiny_patch8_112.arcface_ms1mv3                  0.357941
              vit_tiny_patch8_112.cosface_ms1mv3                  0.353873
dbscan        convnext_atto.cosface_ms1mv3                        0.000000
              convnext_nano.cosface_ms1mv3                       -0.001703
              vit_small_patch8_gap_112.cosface_ms1mv3             0.140184
              vit_tiny_patch8_112.adaface_ms1mv3                  0.000000
              vit_tiny_patch8_112.arcface_ms1mv3                 -0.007368
              vit_tiny_patch8_112.cosface_ms1mv3                 -0.000263
kmeans        convnext_atto.cosface_ms1mv3                        0.004036
              convnext_nano.cosface_ms1mv3                        0.005280
              vit_small_patch8_gap_112.cosface_ms1mv3             0.005449
              vit_tiny_patch8_112.adaface_ms1mv3                  0.004300
              vit_tiny_patch8_112.arcface_ms1mv3                  0.005680
              vit_tiny_patch8_112.cosface_ms1mv3                  0.005482
spectral      convnext_atto.cosface_ms1mv3                        0.006285
              convnext_nano.cosface_ms1mv3                        0.015540
              vit_small_patch8_gap_112.cosface_ms1mv3             0.022109
              vit_tiny_patch8_112.adaface_ms1mv3                  0.007498
              vit_tiny_patch8_112.arcface_ms1mv3                  0.006696
              vit_tiny_patch8_112.cosface_ms1mv3                  0.008982

In [35]:
df.loc[['spectral','kmeans', 'dbscan']].mean()

precision              0.014362
recall                 0.570073
f1                     0.027032
accuracy               0.689929
jaccard                0.013842
fowlkes_mallows        0.066044
rand_index             0.689929
adjusted_rand_index    0.012677
dtype: float64

In [2]:
import pandas as pd

bootstrapped_eval = pd.read_json(
    "/mnt/backup/PeopleGatorNamedFaces/people-gator-named-faces-evaluation/report/cluster_evaluations.v3.vit_small_patch8_gap_112.cosface_ms1mv3.agglomerative.jsonl" , lines=True)

In [12]:
bootstrapped_eval.columns

Index(['assigned_person_names', 'assigned_clusters', 'unassigned_person_names',
       'unassigned_clusters', 'per_cluster_assignment_reports',
       'macro_assignment_report', 'micro_assignment_report',
       'pairwise_report'],
      dtype='str')

In [13]:
pd.DataFrame(bootstrapped_eval['pairwise_report'].tolist())

,true_positives,false_positives,true_negatives,false_negatives,accuracy,precision,recall,f1_score,jaccard,fowlkes_mallows,rand_index,adjusted_rand_index
0,879.000000,1.287933e+06,3.209322e+06,366.166667,0.713616,0.000682,0.705930,0.001363,0.000682,0.021942,0.713616,0.456524
1,879.083333,1.292436e+06,3.204752e+06,433.000000,0.712600,0.000680,0.669990,0.001358,0.000679,0.021340,0.712600,0.348995
2,1318.791667,1.286864e+06,3.209844e+06,473.000000,0.713830,0.001024,0.736018,0.002045,0.001023,0.027450,0.713830,0.449753
3,1142.458333,1.271138e+06,3.225884e+06,336.000000,0.717356,0.000898,0.772736,0.001794,0.000898,0.026342,0.717356,0.410873
4,1323.208333,1.290438e+06,3.206378e+06,361.375000,0.713060,0.001024,0.785481,0.002046,0.001024,0.028366,0.713060,0.455906
...,...,...,...,...,...,...,...,...,...,...,...,...
995,1059.833333,1.325482e+06,3.171527e+06,430.750000,0.705254,0.000799,0.711019,0.001596,0.000799,0.023834,0.705254,0.452181
996,1027.666667,1.240370e+06,3.256693e+06,409.375000,0.724179,0.000828,0.715127,0.001654,0.000828,0.024331,0.724179,0.409937
997,1190.500000,1.310174e+06,3.186781e+06,355.000000,0.708674,0.000908,0.770301,0.001814,0.000908,0.026444,0.708674,0.453327
998,1199.291667,1.283969e+06,3.212886e+06,446.375000,0.714479,0.000933,0.728757,0.001864,0.000933,0.026078,0.714479,0.436446
999,1265.208333,1.334067e+06,3.162669e+06,499.125000,0.703331,0.000947,0.717103,0.001892,0.000947,0.026066,0.703331,0.431779

In [ ]:
maybe_ok_clustering_algo =